name = input("Введите имя: ")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
second_name = input("Введите фамилию:")
print("load")
print(f"hello {second_name} {name}")
